apiVersion: v1
kind: List
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: argo-events
      labels:
        type: infrastructure
    spec:
      project: default
      source:
        repoURL: https://github.com/BhawaniSingh/argo-combined-demo.git
        path: infrastructure/argo-events
      destination: &dest
        server: "https://kubernetes.default.svc"
        namespace: argo
      syncPolicy: &policy
        automated:
          prune: true
          selfHeal: true

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: argo-workflows
      labels:
        type: infrastructure
    spec:
      project: default
      source:
        repoURL: https://github.com/BhawaniSingh/argo-combined-demo.git
        path: infrastructure/argo-workflow
      destination: *dest
      syncPolicy: *policy

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: argo
