apiVersion: v1
kind: Service
metadata:
  name: kubecon-demo-filestash
spec:
  ports:
    - name: tcp-kubecon-demo-filestash
      port: 80
      targetPort: 8334
  selector:
    app.kubernetes.io/name: kubecon-demo-filestash
