apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecon-demo-filestash
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubecon-demo-filestash
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubecon-demo-filestash
    spec:
      containers:
        - image: 'machines/filestash:latest'
          imagePullPolicy: Always
          name: filestash
          ports:
            - containerPort: 8334
          volumeMounts:
            - mountPath: /app/data/state/config
              name: config-volume
      volumes:
        - configMap:
            items:
              - key: kubecon-demo-filestash-config.json
                path: config.json
            name: kubecon-demo-filestash-cm
          name: config-volume