apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- filestash-deployment.yaml
- filestash-service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: kubecon-demo-filestash-cm
  files:
  - kubecon-demo-filestash-config.json
