apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-workflows/v3.1.13/manifests/install.yaml
- workflow-controller-configmap.yaml

patchesStrategicMerge:
- argo-server-service.yaml
- argo-binding.yaml
- argo-server-binding.yaml
